name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Run UI and API tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [api, ui]  # run each as a separate job for parallelism

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (UI tests only)
        if: matrix.project == 'ui'
        run: npx playwright install --with-deps

      - name: Run Playwright tests - ${{ matrix.project }}
        run: npx playwright test --project=${{ matrix.project }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report
